export { default as FeedbackSection } from './Feedback'
export { default as IntroductionSection } from './Introduction'
export { default as BookSection } from './Book'
export { default as FounderSection } from './Founder'
export { default as ReportSection } from './Report'