export { default as CommunityCard } from './Community'
export { default as InsuranceCard } from './Insurance'
export { default as UpcomingCard } from './Upcoming'
export { default as InstaCard } from './Insta'
export { default as ProductCard } from './Product'
export { default as FeedbackCard } from './Feedback'
export { default as VideoCard } from './Video'
export { default as MediaCard } from './Media'
export { default as MemberCard } from './Member'
export { default as MemberRowCard } from './MemberRow'
export { default as ReviewCard } from './Review'

export { default as BigCourseCard } from './BigCourse'
export { default as CourseCard } from './Course'
export { default as TeacherProfileCard } from './TeacherProfile'

// Blog Type
export { default as BigBlogCard } from './Blogs/BigBlog'
export { default as BlogCard } from './Blogs/RegularBlog'
export { default as SmallBlogCard } from './Blogs/SmallBlog'