export { default as CommunityCard } from './Community'
export { default as BlogCard } from './Blog'
export { default as InsuranceCard } from './Insurance'
export { default as UpcomingCard } from './Upcoming'
export { default as InstaCard } from './Insta'
export { default as ProductCard } from './Product'
export { default as FeedbackCard } from './Feedback'
export { default as CourseCard } from './Course'