export { default as ArrowUpIcon } from './arrowup'
export { default as ArrowDownIcon } from './arrowdown'
export { default as HamburgerIcon } from './hamburger'
export { default as SearchIcon } from './search'
export { default as StarIcon } from './star'
export { default as CloseIcon } from './close'
export { default as CheckIcon } from './check'
export { default as UpdownIcon } from './updown'

export { default as PhoneIcon } from './phone'
export { default as WorldIcon } from './world'
export { default as InstagramIcon } from './instagram'
export { default as FacebookIcon } from './facebook'
export { default as TwitterIcon } from './twitter'

export { default as CheckRoundedIcon } from './checkrounded'
export { default as SandClockIcon } from './sandclockrounded'