export { default as Homepage } from './Homepage'
export { default as Article } from './Article'
export { default as AboutUsPage } from './AboutUsPage'
export { default as WhatHypnoBirthing } from './WhatHypnoBirthing'
export { default as OurCommunity } from './OurCommunity'
export { default as FaqPage } from './FaqPage'
