export { default as BannerSkeleton } from './Banner'
export { default as ImageSkeleton } from './Image'
export { default as BigReviewCardSkeleton } from './BigReviewCard'
export { default as SmallReviewCardSkeleton } from './SmallReviewCard'
export { default as BenefitCardSkeleton } from './Benefit'
export { default as NormalTextSkeleton } from './NormalText'
export { default as TwoLineCardSkeleton } from './TwoLine'
export { default as ContactFormCardSkeleton } from './ContactForm'
export { default as TeacherCardSkeleton } from './Teacher'
export { default as SmallBlogSkeletonCard } from './SmallBlog'
export { default as BigBlogSkeletonCard } from './BigBlog'

export { default as SmallCourseSkeletonCard } from './SmallCourse'