export { default as IntroductionSection } from './Introduction'
export { default as AboutClassSection } from './AboutClass'
export { default as SubmitSection } from './Submit'
export { default as FaqSection } from './Faq'
export { default as RelatedCoursesSection } from './RelatedCourses'
export { default as MyContactsSection } from './MyContacts'
export { default as FeedbackSection } from './Feedback'